package uk.gov.hmcts.reform.cmc.performance

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class MakeClaim extends Simulation {

	val httpProtocol = http
		.baseURL("https://localhost:3010")
		.inferHtmlResources(BlackList(""".*\.js.*""", """.*\.css.*""", """.*\.gif.*""", """.*\.jpeg.*""", """.*\.jpg.*""", """.*\.ico.*""", """.*\.woff.*""", """.*\.(t|o)tf.*""", """.*\.png.*"""), WhiteList())
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-GB,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0")

	val headers_0 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Upgrade-Insecure-Requests" -> "1")

	val headers_2 = Map(
		"Accept-Encoding" -> "gzip, deflate",
		"Pragma" -> "no-cache")

    val uri1 = "localhost"
    val uri2 = "http://detectportal.firefox.com/success.txt"

	val scn = scenario("MakeClaim")
		.exec(http("request_0")
			.post("https://" + uri1 + ":8000/login?response_type=code&state=b81b3a82-941c-45af-bb6d-066d2a4d9729&client_id=cmc_citizen&redirect_uri=https://localhost:3010/receiver")
			.headers(headers_0)
			.formParam("username", "civilmoneyclaims+test2@gmail.com")
			.formParam("password", "Password12")
			.formParam("continue", "https://localhost:3010/receiver?state=b81b3a82-941c-45af-bb6d-066d2a4d9729")
			.formParam("upliftToken", "")
			.formParam("response_type", "code")
			.formParam("_csrf", "RaL0VueI-pQxqIpxAzsE9Jsr33_tWV4En42Y")
			.formParam("redirect_uri", "https://localhost:3010/receiver")
			.formParam("client_id", "cmc_citizen")
			.formParam("scope", "")
			.formParam("state", "b81b3a82-941c-45af-bb6d-066d2a4d9729")
			.resources(http("request_1")
			.get("/analytics"),
            http("request_2")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(6)
		.exec(http("request_3")
			.get("/claim/eligibility")
			.headers(headers_0)
			.resources(http("request_4")
			.get("/analytics"),
            http("request_5")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_6")
			.get("/claim/eligibility/claim-value")
			.headers(headers_0),
            http("request_7")
			.get("/analytics"),
            http("request_8")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(2)
		.exec(http("request_9")
			.post("/claim/eligibility/claim-value")
			.headers(headers_0)
			.formParam("_csrf", "Ick9Dn7H-1DplSE36UkiI5N6lYdNru0yDfHU")
			.formParam("claimValue", "UNDER_10000")
			.resources(http("request_10")
			.get("/analytics"),
            http("request_11")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_12")
			.post("/claim/eligibility/over-18")
			.headers(headers_0)
			.formParam("_csrf", "h66yRxwu-HD6A5kixR2gHjq9e8d4SO7q6ooU")
			.formParam("eighteenOrOver", "yes")
			.resources(http("request_13")
			.get("/analytics"),
            http("request_14")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_15")
			.post("/claim/eligibility/help-with-fees")
			.headers(headers_0)
			.formParam("_csrf", "T6ALG60I-DrzNbFwS6NHoTw01k7XakDdsuFc")
			.formParam("helpWithFees", "no")
			.resources(http("request_16")
			.get("/analytics"),
            http("request_17")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1000 milliseconds)
		.exec(http("request_18")
			.post("/claim/eligibility/claimant-address")
			.headers(headers_0)
			.formParam("_csrf", "Ul18ZMzu-dyuXTRMOqnG_TTX6SbfVviS67Cw")
			.formParam("claimantAddress", "yes")
			.resources(http("request_19")
			.get("/analytics"),
            http("request_20")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_21")
			.post("/claim/eligibility/defendant-address")
			.headers(headers_0)
			.formParam("_csrf", "x6aPx9ij-OeQxvG_gdT4QbxCh-Uy3UvttCtI")
			.formParam("defendantAddress", "yes")
			.resources(http("request_22")
			.get("/analytics"),
            http("request_23")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(2)
		.exec(http("request_24")
			.post("/claim/eligibility/government-department")
			.headers(headers_0)
			.formParam("_csrf", "F6khVpQF-qppRuyXVOa0iZe5KZjwOR0xkzZs")
			.formParam("governmentDepartment", "no")
			.resources(http("request_25")
			.get("/analytics"),
            http("request_26")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_27")
			.get("/claim/task-list")
			.headers(headers_0),
            http("request_28")
			.get("/analytics"),
            http("request_29")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_30")
			.get("/claim/resolving-this-dispute")
			.headers(headers_0),
            http("request_31")
			.get("/analytics"),
            http("request_32")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_33")
			.post("/claim/resolving-this-dispute")
			.headers(headers_0)
			.formParam("_csrf", "d7OuA5Gw-BdrCIAnr7-Vq7664jtzDFrBg3z0"),
            http("request_34")
			.get("/analytics"),
            http("request_35")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_36")
			.get("/claim/completing-claim")
			.headers(headers_0),
            http("request_37")
			.get("/analytics"),
            http("request_38")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_39")
			.post("/claim/completing-claim")
			.headers(headers_0)
			.formParam("_csrf", "uyfG0ZM3-3-xUydqyd8QEgWvJS7M6eaCgYII")
			.resources(http("request_40")
			.get("/analytics"),
            http("request_41")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_42")
			.get("/claim/claimant-party-type-selection")
			.headers(headers_0),
            http("request_43")
			.get("/analytics"),
            http("request_44")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(2)
		.exec(http("request_45")
			.post("/claim/claimant-party-type-selection")
			.headers(headers_0)
			.formParam("_csrf", "hWvNXoZa-LSOfdFYXDyGJ8k0YLjycQlD_FhM")
			.formParam("type", "individual")
			.resources(http("request_46")
			.get("/analytics"),
            http("request_47")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(12)
		.exec(http("request_48")
			.post("/claim/claimant-individual-details")
			.headers(headers_0)
			.formParam("_csrf", "okolVSJ8-QEhC2TWDBBOdnk1w69b5FMmU3UA")
			.formParam("name", "John Smith")
			.formParam("address[line1]", "221B Baker street")
			.formParam("address[line2]", "")
			.formParam("address[city]", "London")
			.formParam("address[postcode]", "NW1 6XE")
			.formParam("hasCorrespondenceAddress", "false")
			.formParam("correspondenceAddress[line1]", "")
			.formParam("correspondenceAddress[line2]", "")
			.formParam("correspondenceAddress[city]", "")
			.formParam("correspondenceAddress[postcode]", "")
			.resources(http("request_49")
			.get("/analytics"),
            http("request_50")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(2)
		.exec(http("request_51")
			.post("/claim/claimant-dob")
			.headers(headers_0)
			.formParam("known", "true")
			.formParam("_csrf", "S8E0Mnkg-cUHOeVb4NkT6bz9RGHQui5zawOg")
			.formParam("date[day]", "31")
			.formParam("date[month]", "3")
			.formParam("date[year]", "1980")
			.resources(http("request_52")
			.get("/analytics"),
            http("request_53")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(2)
		.exec(http("request_54")
			.post("/claim/claimant-mobile")
			.headers(headers_0)
			.formParam("_csrf", "QUicbqEd-t6ZCUSowHkm7sc-wvbS4EovlCMg")
			.formParam("number", "07123456789")
			.resources(http("request_55")
			.get("/analytics"),
            http("request_56")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_57")
			.get("/claim/defendant-party-type-selection")
			.headers(headers_0),
            http("request_58")
			.get("/analytics"),
            http("request_59")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_60")
			.post("/claim/defendant-party-type-selection")
			.headers(headers_0)
			.formParam("_csrf", "scR3Eolk-WokBLo7Q7_HnnefpvR_WjoXkxoI")
			.formParam("type", "individual")
			.resources(http("request_61")
			.get("/analytics"),
            http("request_62")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(8)
		.exec(http("request_63")
			.post("/claim/defendant-individual-details")
			.headers(headers_0)
			.formParam("_csrf", "pYuhieQS-V4FsUI2PdsRd5Jid6sV7ynVSsR8")
			.formParam("name", "Robert Lee")
			.formParam("address[line1]", "123 Johns lane")
			.formParam("address[line2]", "")
			.formParam("address[city]", "London")
			.formParam("address[postcode]", "SW1 2AX")
			.resources(http("request_64")
			.get("/analytics"),
            http("request_65")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(3)
		.exec(http("request_66")
			.post("/claim/defendant-email")
			.headers(headers_0)
			.formParam("_csrf", "VsScCiki-MmCzJ7F31MKgktmX01lsqyFSetk")
			.formParam("address", "")
			.resources(http("request_67")
			.get("/analytics"),
            http("request_68")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_69")
			.get("/claim/amount")
			.headers(headers_0)
			.resources(http("request_70")
			.get("/analytics"),
            http("request_71")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(7)
		.exec(http("request_72")
			.post("/claim/amount")
			.headers(headers_0)
			.formParam("_csrf", "pXpRSQkZ-CZpOk1PNAzBJgyMYk8lLHyrQ3PM")
			.formParam("rows[0][reason]", "Performance test")
			.formParam("rows[0][amount]", "202")
			.formParam("rows[1][reason]", "")
			.formParam("rows[1][amount]", "")
			.formParam("rows[2][reason]", "")
			.formParam("rows[2][amount]", "")
			.formParam("rows[3][reason]", "")
			.formParam("rows[3][amount]", "")
			.resources(http("request_73")
			.get("/analytics"),
            http("request_74")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(2)
		.exec(http("request_75")
			.post("/claim/interest")
			.headers(headers_0)
			.formParam("_csrf", "CS6foQlk-vF1VESQGil-xB09Pdewa7VIy0UE")
			.formParam("rate", "")
			.formParam("reason", "")
			.formParam("type", "no interest")
			.resources(http("request_76")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_77")
			.get("/claim/fees")
			.headers(headers_0),
            http("request_78")
			.get("/analytics"),
            http("request_79")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_80")
			.post("/claim/fees")
			.headers(headers_0)
			.formParam("_csrf", "JqVHSvQ8-stsfptzU-JpWt7GVhlM-AYIs6DI")
			.resources(http("request_81")
			.get("/analytics"),
            http("request_82")
			.get(uri2 + "")
			.headers(headers_2),
            http("request_83")
			.post("/claim/total")
			.headers(headers_0)
			.formParam("_csrf", "AlIGyUtm-mv0mu8Od-GMVpB2qF3o0yPGsfgY"),
            http("request_84")
			.get("/analytics"),
            http("request_85")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_86")
			.get("/claim/reason")
			.headers(headers_0)
			.resources(http("request_87")
			.get("/analytics"),
            http("request_88")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(4)
		.exec(http("request_89")
			.post("/claim/reason")
			.headers(headers_0)
			.formParam("_csrf", "O6ZJFCaV-y1CUyn7zmNeglsLC_1X53J8j41c")
			.formParam("reason", "Performance test")
			.resources(http("request_90")
			.get("/analytics"),
            http("request_91")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(1)
		.exec(http("request_92")
			.get("/claim/check-and-send")
			.headers(headers_0)
			.resources(http("request_93")
			.get("/analytics"),
            http("request_94")
			.get(uri2 + "")
			.headers(headers_2)))
		.pause(2)
		.exec(http("request_95")
			.post("/claim/check-and-send")
			.headers(headers_0)
			.formParam("_csrf", "g1iqx2vI-tJQOYQkhFx7Oyhcg6_BLiatRZSY")
			.formParam("signed", "true")
			.formParam("type", "basic"))

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}